name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 build:
   runs-on: ubuntu-latest  # Run on Ubuntu virtual machines

    steps:
      - uses: actions/checkout@v3  # Checkout code from GitHub
      - name: Set up JDK 1.8  # Install Java Development Kit
        uses: actions/setup-java@v3
        with:
          java-version: '1.8'
      - name: Cache Gradle packages  # Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle') }}
      - name: Run gradle build  # Build the Android project
        run: ./gradlew build
