name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run linting
        run: uses: actions/eslint@v3

      - name: Upload lint report (if applicable)
        uses: actions/upload-artifact@v2
        with:
          name: lint_report.html  # Adjust filename if necessary
          path: path/to/your/lint/report/file  # Update with the actual path
